### PR TITLE
Add GraphViz dot visualizations for IR uGraphs.

### PR DESCRIPTION
**Pull request by mbartling**
Add the ability to FINALLY visualize graphs in uTensor code gen. Defaults to writing graphs to ./graphs/graph.gv.pdf

`brew install graphviz`
`myGraph.viz_graph()`
graph

### CODE REVIEW

**Comment by neil-tan** [comment]
@mbartling awesome stuff. Is there a path to extend this to display op_type, dimension, etc?

**Comment by mbartling** [comment]
@neil-tan It should be trivial to make these extensions, Graphviz is pretty powerful. I just made this quick PR as a placeholder for future extensions etc. I think just the general graph and node names is sufficient to help with like 95% of our bugs.

**Comment by dboyliao** [comment]
Looks good.
Maybe I'll patch this PR so the tensor names go to the edges and node names go to the nodes in the graph image.

Now it's hard to infer what do we mean by a "graph".
Can be either a computational graph or literally an image. XD

**Comment by dboyliao** [comment]
One quick thought: I don't think it should be a method of `uTensorGraph`.
It should be a function or a method of other objects (such as a `uTensorGraphVisualizer`, I assume).

I feel like it's against the single responsibility principle which means we're making `uTensorGraph` being responsible for too many tasks.
In your implementation, `uTensorGraph` need to carry computation informations (`ops`, `tensors`, blah blah blah) and the visualization.
That's too much.

**Comment by mbartling** [comment]
@dboyliao I am not convinced that this should be a separate module or method as it is solely for debugging purposes. Every graph we have has a different interface (tf graphs, torch, etc.) and the one golden unifier is our IR graph. Therefore, it makes sense to keep this here.

**Comment by dboyliao** [comment]
If it's solely for debugging purpose, why not add to a debugging util module?
As you adding more and more irrelevant methods (other than generating code) to the graph, it takes more time for future developer to read it.

**Comment by dboyliao** [comment]
Take `tensorflow` as example, they didn't make visualization tool as part of TF itself but rather separate it out.
Not even a python submodule but another python package, `tensorboard`.
If following your argument, why not they make the visualization/analysis tools all methods of `tf.Graph`?
And you can imagine, how complex `tf.Graph` would be if they did.

**Comment by mbartling** [comment]
I am ok with adding it to a debugging module, currently it is treated as debugging as the import only occurs on the function call. I just want to make sure this tool is available to our devs. Neil and I found it extremely valuable when doing the CMSIS stuff

**Comment by dboyliao** [comment]
Since the viz method is in the ir code already, closing this PR.

**Pull request closed without merging**
