### PR TITLE
Tf update 2.3.1

### PR DESCRIPTION
**Pull request by victorromeo**
This commit is for TensorFlow 2.3.1 support as default minimum

### CODE REVIEW

**Comment by dboyliao** [comment]
@victorromeo What is the version of your `pipenv`?

**Comment by victorromeo** [comment]
pipenv, version 11.9.0

**Comment by dboyliao** [comment]
That's too old.
Please update your `pipenv` and do the update again.

**Comment by dboyliao** [comment]
After you update your `pipenv`, I recommend you to update the lock file by running:
```bash
$ pipenv install -d --skip-lock
$ pipenv lock
```

Don't update tensorflow by `pipenv install tensorflow==2.3.1`

**Comment by dboyliao** [comment]
The idea is to keep package dependencies defined in `setup.py` only and use lock file to take care of the dev environment.

**Comment by victorromeo** [comment]
Sure.  In progress. Will let you know once complete.

**Comment by dboyliao** [comment]
@victorromeo You're really helping.
I know updating the lock file is not easy.
`pipenv lock` normally takes long time to finish for a project like this one.

**Comment by dboyliao** [comment]
Hey, @victorromeo.
I am working on #138 and I accidentally update TF to 2.3.1.
So I'm about to close this PR, hope you won't mind.

Also, I find out an issue in your last PR (actually not your issue but google's) and I'd like to share with you.
In `utensor_cgen`, we use [`ortools`](https://developers.google.com/optimization/introduction/python) for tensor memory allocation optimization planning.
However, it's fighting Tensorflow where the program will crash if you switch the import order.
As a result, you must import `utensor_cgen` BEFORE import any tensorflow code.
I also update to tests code in #138 so you don't have to worry about it.

Good job!

**Comment by victorromeo** [comment]
Understood. Thanks for the update.

**Pull request closed without merging**
