### PR TITLE
Makefile Error / close #19

### LINKED ISSUE #19: test make error
cp: cannot create regular file 'idx_data/': Not a directory 

os: ubuntu 16

### PR DESCRIPTION
**Pull request by Knight-X**
fix mirror error in makefile for test #19

### CODE REVIEW

**Comment by dboyliao** [comment]
I think it's a bug and you should not fix it in `Makefile` since the python code **should** create that directory.
I think it's much more appropriate if you fix it in `utensor_cgen/core.py` rather than `Makefile`.

**Comment by Knight-X** [comment]
thanks your reviewing. I got your point and revise it later.

**Comment by Knight-X** [comment]
hmm..., I push another commit on this pr. could you delete this pr and I will make pr separately ?

**Comment by dboyliao** [comment]
I don't think it's necessary.
Merge now!

**Pull request merged**
